# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Project.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def Data_File_Action(self) :
        print("Data_File Button working")
    
    def comboBox_Action(self) :
        print("comboBox working")
    
    def pushButton_4_Action(self) :
        print("pushButton_4 working")

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(120, 250, 211, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.Input_Text = QtWidgets.QTextEdit(self.centralwidget)
        self.Input_Text.setGeometry(QtCore.QRect(30, 70, 401, 141))
        self.Input_Text.setObjectName("Input_Text")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 220, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 50, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 290, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(40, 310, 391, 121))
        self.textEdit_2.setObjectName("textEdit_2")
        self.Data_File = QtWidgets.QComboBox(self.centralwidget)
        self.Data_File.setGeometry(QtCore.QRect(338, 220, 91, 22))
        self.Data_File.setObjectName("Data_File")
        self.Data_File.addItem("")
        self.Data_File.addItem("")
        self.Data_File.addItem("")
        self.Data_File.addItem("")
        self.Data_File.addItem("")
        self.Data_File.addItem("")
        self.Data_File.addItem("")
        self.Data_File.addItem("")
        self.Data_File.addItem("")
        self.Data_File.addItem("")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(340, 250, 91, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.textEdit_2.raise_()
        self.comboBox.raise_()
        self.Input_Text.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.Data_File.raise_()
        self.pushButton_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuAlgorithm_Project = QtWidgets.QMenu(self.menubar)
        self.menuAlgorithm_Project.setObjectName("menuAlgorithm_Project")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAlgorithm_Project.menuAction())
        self.Data_File.activated[str].connect(self.Data_File_Action)
        self.comboBox.activated[str].connect(self.comboBox_Action)
        self.pushButton_4.clicked.connect(self.pushButton_4_Action)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Longest Common Subsequence"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Shortest Common Supersequence"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Longest Increasing Subsequence problem"))
        self.comboBox.setItemText(3, _translate("MainWindow", "The Levenshtein distance (Edit distance) problem"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Matrix Chain Multiplication"))
        self.comboBox.setItemText(5, _translate("MainWindow", "0–1 Knapsack problem"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Partition problem"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Rod Cutting"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Coin change problem"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Word Break Problem"))
        self.pushButton.setText(_translate("MainWindow", "Chose File"))
        self.pushButton_2.setText(_translate("MainWindow", "Input"))
        self.pushButton_3.setText(_translate("MainWindow", "Output"))
        self.Data_File.setItemText(0, _translate("MainWindow", "Data_Set 1"))
        self.Data_File.setItemText(1, _translate("MainWindow", "Data_Set 2"))
        self.Data_File.setItemText(2, _translate("MainWindow", "Data_Set 3"))
        self.Data_File.setItemText(3, _translate("MainWindow", "Data_Set 4"))
        self.Data_File.setItemText(4, _translate("MainWindow", "Data_Set 5"))
        self.Data_File.setItemText(5, _translate("MainWindow", "Data_Set 6"))
        self.Data_File.setItemText(6, _translate("MainWindow", "Data_Set 7"))
        self.Data_File.setItemText(7, _translate("MainWindow", "Data_Set 8"))
        self.Data_File.setItemText(8, _translate("MainWindow", "Data_Set 9"))
        self.Data_File.setItemText(9, _translate("MainWindow", "Data_Set 10"))
        self.pushButton_4.setText(_translate("MainWindow", "OK"))
        self.menuAlgorithm_Project.setTitle(_translate("MainWindow", "Algorithm Project"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())